#!/usr/bin/env python3
"""
run_hdqn_experiment.py

Run the LayerNorm HDQN MAPC experiment using a generated hyperparameter
configuration.

The program can load a configuration generated by
`tune_hdqn_hyperparameters.py` from `configs.csv`:

    python run_hdqn_experiment.py \
        --config-id cfg_XXXXXXXXXXXXXXX \
        --config-file ./hdqn_hyperparameter_tuning/configs.csv

or by configuration row/index:

    python run_hdqn_experiment.py \
        --config-index 731 \
        --config-file ./hdqn_hyperparameter_tuning/configs.csv

It also accepts a configuration JSON directly, which is useful when the
tuner wants to launch a configuration without writing/reading a CSV.

Without --config-id / --config-index / --config-json, the exact original
baseline hyperparameters from the supplied experiment are used.

Important:
    - The HDQN architecture is not changed here.
    - LayerNorm remains wherever it is implemented in your QNetwork.
    - Only the hyperparameters passed through MapcDQNAgentFactory are changed.
    - Each run creates a fresh agent factory with a deterministic seed.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import jax
import numpy as np
import optax
from tqdm import tqdm

from mapc_cmab.agents.mapc_cmab_agent_factory import MapcDQNAgentFactory
from mapc_cmab.envs.scenario_impl import small_office_scenario
from mapc_cmab.plots.throughput_analysis.throughput_ci import (
    analyze_and_plot_throughputs,
)


# ============================================================
# Constants
# ============================================================

DEFAULT_D_AP = 10.0
DEFAULT_N_STEPS = 10_000

LEVELS = ("l1", "l2", "l3", "l4")


# ============================================================
# Mixed scenario
# ============================================================

class MixScen:
    def __init__(
        self,
        scenario_factory,
        d_sta_1: int,
        d_sta_2: int,
        d_ap: float = DEFAULT_D_AP,
        max_steps: int = DEFAULT_N_STEPS,
    ):
        self.scen1 = scenario_factory(
            d_ap=d_ap,
            d_sta=d_sta_1,
        )
        self.scen2 = scenario_factory(
            d_ap=d_ap,
            d_sta=d_sta_2,
        )

        self.step = 0
        self.switch_steps = max_steps // 2

        self.data_rate_fn1 = jax.jit(
            self.scen1.data_rate_fn
        )
        self.data_rate_fn2 = jax.jit(
            self.scen2.data_rate_fn
        )

        self.data_rate_fn = self.data_rate_fn1
        self.associations = self.scen1.associations

        self.str_repr = (
            f"mix_scen_ap_{d_ap:g}_"
            f"dsta_{d_sta_1}_{d_sta_2}_"
            f"s{max_steps}"
        )

    def __call__(self, key, link_ap_sta):
        self.step += 1

        if self.step == self.switch_steps:
            self.data_rate_fn = (
                self.data_rate_fn2
                if self.data_rate_fn is self.data_rate_fn1
                else self.data_rate_fn1
            )

        return self.data_rate_fn(
            key,
            link_ap_sta=link_ap_sta,
        )

    def reset(self):
        self.data_rate_fn = self.data_rate_fn1
        self.step = 0


# ============================================================
# Baseline configuration
# ============================================================

def baseline_configuration():
    """
    Exact baseline from the supplied LayerNorm HDQN program.
    """
    return {
        "optimizer": (
            "adam",
            "adam",
            "adam",
            "adam",
        ),
        "lr": (
            1e-3,
            1e-3,
            1e-3,
            1e-3,
        ),
        "buffer": (
            1000,
            1000,
            1000,
            1000,
        ),
        "batch": (
            32,
            32,
            32,
            32,
        ),
        "replay_steps": (
            1,
            1,
            1,
            1,
        ),
        "eps_min": (
            0.1,
            0.1,
            0.1,
            0.1,
        ),
        "eps_decay": (
            0.995,
            0.995,
            0.999,
            0.995,
        ),
        "weight_decay": (
            1e-4,
            1e-4,
            1e-4,
            1e-4,
        ),
    }


# ============================================================
# Configuration loading
# ============================================================

def normalize_config(cfg: dict) -> dict:
    """
    CSV JSON converts tuples to lists. Convert everything into the
    tuple-based representation expected by this runner.
    """
    required = {
        "optimizer",
        "lr",
        "buffer",
        "batch",
        "replay_steps",
        "eps_min",
        "eps_decay",
        "weight_decay",
    }

    missing = required.difference(cfg)
    if missing:
        raise ValueError(
            f"Configuration is missing fields: {sorted(missing)}"
        )

    normalized = {
        "optimizer": tuple(str(x) for x in cfg["optimizer"]),
        "lr": tuple(float(x) for x in cfg["lr"]),
        "buffer": tuple(int(x) for x in cfg["buffer"]),
        "batch": tuple(int(x) for x in cfg["batch"]),
        "replay_steps": tuple(int(x) for x in cfg["replay_steps"]),
        "eps_min": tuple(float(x) for x in cfg["eps_min"]),
        "eps_decay": tuple(float(x) for x in cfg["eps_decay"]),
        "weight_decay": tuple(float(x) for x in cfg["weight_decay"]),
    }

    for field, values in normalized.items():
        if len(values) != 4:
            raise ValueError(
                f"{field} must contain exactly 4 values, got {values}"
            )

    for i in range(4):
        if normalized["batch"][i] > normalized["buffer"][i]:
            raise ValueError(
                f"L{i+1}: batch size "
                f"{normalized['batch'][i]} exceeds replay buffer "
                f"{normalized['buffer'][i]}"
            )

        if normalized["lr"][i] <= 0:
            raise ValueError(
                f"L{i+1}: learning rate must be > 0."
            )

        if not 0 < normalized["eps_min"][i] <= 1:
            raise ValueError(
                f"L{i+1}: epsilon_min must be in (0, 1]."
            )

        if not 0 < normalized["eps_decay"][i] < 1:
            raise ValueError(
                f"L{i+1}: epsilon_decay must be in (0, 1)."
            )

    return normalized


def read_config_from_csv(config_file: Path, config_id: str) -> dict:
    if not config_file.exists():
        raise FileNotFoundError(
            f"Config file not found: {config_file}"
        )

    with config_file.open(
        "r",
        newline="",
        encoding="utf-8",
    ) as f:
        reader = csv.DictReader(f)

        for row in reader:
            if row["config_id"] == config_id:
                return normalize_config(
                    json.loads(row["configuration_json"])
                )

    raise ValueError(
        f"Configuration ID {config_id!r} was not found in "
        f"{config_file}"
    )


def read_config_by_index(config_file: Path, config_index: int) -> dict:
    if config_index < 1:
        raise ValueError(
            "--config-index is 1-based and must be >= 1."
        )

    with config_file.open(
        "r",
        newline="",
        encoding="utf-8",
    ) as f:
        reader = csv.DictReader(f)

        for row_number, row in enumerate(reader, start=1):
            if row_number == config_index:
                return normalize_config(
                    json.loads(row["configuration_json"])
                )

    raise ValueError(
        f"Configuration index {config_index} was not found in "
        f"{config_file}"
    )


# ============================================================
# Optimizer / agent construction
# ============================================================

def make_optimizer(
    name: str,
    learning_rate: float,
    weight_decay: float,
):
    name = name.lower()

    if name == "adam":
        return optax.adam(learning_rate)

    if name == "adamw":
        return optax.adamw(
            learning_rate=learning_rate,
            weight_decay=weight_decay,
        )

    raise ValueError(
        f"Unsupported optimizer {name!r}. "
        f"Expected 'adam' or 'adamw'."
    )


def make_agent_params(
    cfg: dict,
    level_index: int,
) -> dict:
    return {
        "optimizer": make_optimizer(
            cfg["optimizer"][level_index],
            cfg["lr"][level_index],
            cfg["weight_decay"][level_index],
        ),
        "experience_replay_buffer_size": (
            cfg["buffer"][level_index]
        ),
        "experience_replay_batch_size": (
            cfg["batch"][level_index]
        ),
        "experience_replay_steps": (
            cfg["replay_steps"][level_index]
        ),
        "epsilon_min": (
            cfg["eps_min"][level_index]
        ),
        "epsilon_decay": (
            cfg["eps_decay"][level_index]
        ),
    }


def create_agent_factory(
    scenario,
    cfg: dict,
    args,
    seed: int,
):
    """
    Feed generated per-level hyperparameters into the exact same
    MapcDQNAgentFactory used by the original program.
    """
    return MapcDQNAgentFactory(
        associations=scenario.associations,
        agent_params_lvl1=make_agent_params(cfg, 0),
        agent_params_lvl2=make_agent_params(cfg, 1),
        agent_params_lvl3=make_agent_params(cfg, 2),
        agent_params_lvl4=make_agent_params(cfg, 3),
        n_tx_power_levels=args.n_tx_power_levels,
        n_links=args.n_links,
        seed=seed,
    )


# ============================================================
# Experiment
# ============================================================

def run_single_experiment(
    scenario,
    cfg: dict,
    args,
    run_number: int,
    key,
):
    """
    One completely fresh HDQN run.

    The environment action/reward loop remains the same as in the
    supplied program:
        agent.sample(previous_reward)
        -> environment
        -> current reward becomes next previous_reward
    """
    factory = create_agent_factory(
        scenario=scenario,
        cfg=cfg,
        args=args,
        seed=args.seed + run_number,
    )

    agent = factory.create_hierarchical_DQN_cmapc_agent(
        logger=None
    )

    throughputs = np.zeros(
        args.n_steps,
        dtype=np.float32,
    )

    previous_throughput = 0.0

    scenario.reset()

    for step in tqdm(
        range(1, args.n_steps),
        desc=f"run_number: {run_number}",
        leave=True,
    ):
        key, step_key = jax.random.split(key)

        tx_config = agent.sample(
            reward=previous_throughput
        )

        data_rate = scenario(
            step_key,
            tx_config,
        )

        data_rate = float(data_rate)

        throughputs[step] = data_rate
        previous_throughput = data_rate

    return throughputs


def run_experiments(
    scenario,
    cfg: dict,
    args,
):
    """
    Every Monte-Carlo run gets a fresh factory/agent.

    The same JAX run keys are reused for the selected configuration,
    making it directly comparable with other configurations when the
    same seed is used.
    """
    run_keys = jax.random.split(
        jax.random.PRNGKey(args.seed),
        args.n_runs,
    )

    throughputs = np.zeros(
        (args.n_runs, args.n_steps),
        dtype=np.float32,
    )

    for run_number in range(args.n_runs):
        throughputs[run_number] = (
            run_single_experiment(
                scenario=scenario,
                cfg=cfg,
                args=args,
                run_number=run_number,
                key=run_keys[run_number],
            )
        )

    return throughputs


# ============================================================
# CLI
# ============================================================

def parse_args():
    p = argparse.ArgumentParser(
        description=(
            "Run LayerNorm HDQN using a generated "
            "hyperparameter configuration."
        )
    )

    p.add_argument(
        "--config-file",
        type=Path,
        default=Path(
            "./hdqn_hyperparameter_tuning/configs.csv"
        ),
        help="configs.csv generated by the tuner.",
    )

    group = p.add_mutually_exclusive_group()

    group.add_argument(
        "--config-id",
        type=str,
        default=None,
        help="Configuration ID from configs.csv.",
    )

    group.add_argument(
        "--config-index",
        type=int,
        default=None,
        help=(
            "1-based row/index in configs.csv "
            "(header not counted)."
        ),
    )

    group.add_argument(
        "--config-json",
        type=str,
        default=None,
        help=(
            "Configuration JSON produced by the tuner. "
            "Useful for direct programmatic hand-off."
        ),
    )

    # Scenario / experiment parameters.
    p.add_argument(
        "--d-ap",
        type=float,
        default=10.0,
    )

    p.add_argument(
        "--d-sta-1",
        type=int,
        default=2,
    )

    p.add_argument(
        "--d-sta-2",
        type=int,
        default=4,
    )

    p.add_argument(
        "--n-runs",
        type=int,
        default=50,
    )

    p.add_argument(
        "--n-steps",
        type=int,
        default=10_000,
    )

    p.add_argument(
        "--n-links",
        type=int,
        default=3,
    )

    p.add_argument(
        "--n-tx-power-levels",
        type=int,
        default=4,
    )

    p.add_argument(
        "--seed",
        type=int,
        default=42,
    )

    p.add_argument(
        "--window-size",
        type=int,
        default=100,
    )

    p.add_argument(
        "--step-duration",
        type=float,
        default=0.005,
    )

    p.add_argument(
        "--confidence",
        type=float,
        default=0.99,
    )

    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path("./results"),
    )

    p.add_argument(
        "--filename",
        type=str,
        default=None,
    )

    p.add_argument(
        "--show",
        action="store_true",
    )

    return p.parse_args()


# ============================================================
# Reporting
# ============================================================

def print_configuration(cfg: dict):
    print("\n" + "=" * 100)
    print("HDQN CONFIGURATION")
    print("=" * 100)

    for i in range(4):
        print(
            f"L{i+1}: "
            f"optimizer={cfg['optimizer'][i]}, "
            f"lr={cfg['lr'][i]:.8g}, "
            f"buffer={cfg['buffer'][i]}, "
            f"batch={cfg['batch'][i]}, "
            f"replay_steps={cfg['replay_steps'][i]}, "
            f"epsilon_min={cfg['eps_min'][i]:.8g}, "
            f"epsilon_decay={cfg['eps_decay'][i]:.8g}, "
            f"weight_decay={cfg['weight_decay'][i]:.8g}"
        )

    print("=" * 100)


# ============================================================
# Main
# ============================================================

def main():
    args = parse_args()

    if args.n_runs < 1:
        raise ValueError("--n-runs must be >= 1.")

    if args.n_steps < 2:
        raise ValueError("--n-steps must be >= 2.")

    if not 0 < args.confidence < 1:
        raise ValueError(
            "--confidence must be between 0 and 1."
        )

    # JAX persistent compilation cache.
    jax.config.update(
        "jax_compilation_cache_dir",
        "./jax_cache",
    )
    jax.config.update(
        "jax_persistent_cache_enable_xla_caches",
        "all",
    )

    # --------------------------------------------------------
    # Load selected configuration.
    # --------------------------------------------------------
    if args.config_id is not None:
        cfg = read_config_from_csv(
            args.config_file,
            args.config_id,
        )
        config_label = args.config_id

    elif args.config_index is not None:
        cfg = read_config_by_index(
            args.config_file,
            args.config_index,
        )
        config_label = f"index_{args.config_index}"

    elif args.config_json is not None:
        cfg = normalize_config(
            json.loads(args.config_json)
        )
        config_label = "direct_json"

    else:
        cfg = baseline_configuration()
        config_label = "baseline"

    print_configuration(cfg)

    # --------------------------------------------------------
    # Scenario.
    # --------------------------------------------------------
    scenario = MixScen(
        small_office_scenario,
        args.d_sta_1,
        args.d_sta_2,
        args.d_ap,
        max_steps=args.n_steps,
    )

    # --------------------------------------------------------
    # Filename.
    # --------------------------------------------------------
    if args.filename is None:
        filename = (
            f"hdqn_{config_label}_"
            f"{scenario.str_repr}_"
            f"runs_{args.n_runs}_"
            f"steps_{args.n_steps}"
        )
    else:
        filename = args.filename

    # --------------------------------------------------------
    # Execute.
    # --------------------------------------------------------
    throughputs = run_experiments(
        scenario=scenario,
        cfg=cfg,
        args=args,
    )

    # --------------------------------------------------------
    # Existing throughput analysis / plotting.
    # --------------------------------------------------------
    analyze_and_plot_throughputs(
        throughputs=throughputs,
        window_size=args.window_size,
        step_duration=args.step_duration,
        confidence=args.confidence,
        output_dir=str(args.output_dir),
        filename=filename,
        show=args.show,
    )


if __name__ == "__main__":
    main()
